###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: php-starter-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: _docker/php-fpm
      container_name: php-starter-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./_docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

